[package]
name = "pennyarcade"
version = "0.1.0"
authors = ["Mike Steder <steder@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "^0.4.19"
structopt = "^0.3.13"
url = "*"
hyper = "*"